function s=default_scenario()
s=struct('zone',3,'location',0.5,'faultType','AG','Rf',2,...
 'pvMW',4,'irradiance',1,'loadScale',1,'unbalance',0.03,'sourceScale',1,...
 'failedBreaker',0,'transferTrip',true,'faultEnabled',true);
end
